name: Vulnerable Workflow
on: push
jobs:
  insecure_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Echo secrets 1
        run: echo "odczytany sekret to ${{ secrets.SEKRET }}"

      - name: Echo secrets 2
        run: echo "odczytany sekret to ${{ secrets.SEKRET }}" | base64

      - name: Echo secrets 3
        run: echo "odczytany sekret to ${{ secrets.SEKRET }}" | base32
